#!/bin/bash
# The logic to start up your application should be put in this
# script. The application will work only if it binds to
# $OPENSHIFT_INTERNAL_IP:8080

source $OPENSHIFT_DATA_DIR/$OPENSHIFT_APP_NAME/bin/activate
WORKERS=3
LOGFILE=$OPENSHIFT_LOG_DIR/gunicorn.log
PIDFILE=$OPENSHIFT_DATA_DIR/gunicorn.pid
python $OPENSHIFT_REPO_DIR/diy/manage.py run_gunicorn $OPENSHIFT_INTERNAL_IP:$OPENSHIFT_INTERNAL_PORT --daemon --workers=$WORKERS --pid=$PIDFILE --log-file=$LOGFILE --log-level=info
