#!/bin/bash
# The logic to stop your application should be put in this script.
PIDFILE=${OPENSHIFT_DATA_DIR}gunicorn.pid
if [ -f $PIDFILE ]; then
    PID=`cat $PIDFILE`
    rm $PIDFILE
    kill -15 $PID
fi
